### ISSUE TITLE
HTTP error 503

### ISSUE THREAD

**Issue by serenosaur** [adror1/nwslR#51]
I receive error this in response to calling the `get_adv_team_stats()` function:
`Error in open.connection(con, "rb") : HTTP error 503.`

**Comment by adror1** [comment]
Hi! Thanks for letting us know about this. I suspect that it has to do with a change in structure of the league's website. I'll try to get a solution to this ASAP.

**Comment by adror1** [comment]
I just uploaded a scraped csv, `adv_team_stats` that has all the information from 2016-2019! Hope this is a useful fix.
