### ISSUE TITLE
Leading space in nation column

### ISSUE THREAD

**Issue by SebaStad** [adror1/nwslR#56]
Hi there,

is there a reason the nation columns do contain leading spaces is in " USA" instead of "USA"? Feels a bit unpractical, when one wants to filter by nation or similar.
If you already documented this and i missed it, sorry.

Kind Regards

**Comment by adror1** [comment]
No, there's no reason and I keep forgetting to go back and fix it. I'll try to do it this afternoon! So sorry.

**Comment by adror1** [comment]
Just fixed this and merged it!
